import {useState} from 'react';
import {useAppState} from '../context/AppStateContext';
import {isInternalUser} from '../lib/permissions';
import {getSupabase} from '../lib/supabaseClient';
import {localDay,localDateTime,periodEnd,rangeMinutes,timeCsv,type Period} from '../lib/timeReporting';
import type {TimeEntry} from '../lib/types';
export function TimeTrackingPage(){
 const {data,currentUser,cloud,supportSnapshot,activeTimer,startTimer,stopTimer,refresh,deleteTimeEntry}=useAppState();
 const [tab,setTab]=useState('tracker'),[period,setPeriod]=useState<Period>('monthly');
 const [from,setFrom]=useState(()=>localDay().slice(0,8)+'01'),[through,setThrough]=useState(()=>periodEnd(localDay(),'monthly'));
 const [client,setClient]=useState(''),[project,setProject]=useState(''),[person,setPerson]=useState(''),[billable,setBillable]=useState('');
 const [timerProject,setTimerProject]=useState(''),[timerTask,setTimerTask]=useState('');
 const [editing,setEditing]=useState<TimeEntry|null|undefined>(undefined),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const team=['owner','admin','supervisor'].includes(currentUser?.role||'');
 if(!isInternalUser(currentUser)||!cloud)return <p>Time tracking is available to staff in the shared workspace.</p>;
 const rows=data.timeEntries.map(e=>({e,minutes:rangeMinutes(e,from,through),p:data.projects?.find(p=>p.id===e.projectId)||data.projects?.find(p=>p.id===data.workItems.find(w=>w.id===e.workItemId)?.projectId)})).filter(({e,minutes,p})=>minutes>0&&(tab!=='team'?e.userId===currentUser?.id:!person||e.userId===person)&&(!client||p?.clientId===client)&&(!project||p?.id===project)&&(!billable||e.billable===(billable==='yes'))).sort((a,b)=>b.e.startedAt.localeCompare(a.e.startedAt));
 const total=rows.reduce((sum,r)=>sum+r.minutes,0), billed=rows.reduce((sum,r)=>sum+(r.e.billable?r.minutes:0),0);
 async function run(fn:()=>Promise<unknown>){if(busy)return;setBusy(true);setError('');try{await fn();await refresh?.();}catch(e){setError(e instanceof Error?e.message:typeof e==='object'&&e&&'message' in e?String(e.message):'Could not save time.');}finally{setBusy(false);}}
 function exportRows(){const text=timeCsv([['Employee','Client','Project','Task','Started','Ended','Hours in selected period','Billable','Note'],...rows.map(({e,p,minutes})=>[data.users.find(u=>u.id===e.userId)?.name||e.userId,data.clients.find(c=>c.id===p?.clientId)?.name||'',p?.name||'',data.workItems.find(w=>w.id===e.workItemId)?.title||'Project time',e.startedAt,e.endedAt,(minutes/60).toFixed(4),e.billable?'Yes':'No',e.note])]);const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`sunrose-hours-${from}-${through}.csv`;a.click();URL.revokeObjectURL(url);}
 return <div className="stack"><h1>Time tracking</h1><div className="row"><button className="btn" aria-pressed={tab==='tracker'} onClick={()=>setTab('tracker')}>My time</button><button className="btn" aria-pressed={tab==='timesheet'} onClick={()=>setTab('timesheet')}>My timesheet</button>{team&&<button className="btn" aria-pressed={tab==='team'} onClick={()=>setTab('team')}>Team report</button>}</div>
 {tab==='tracker'&&!supportSnapshot&&<section className="card stack"><h2>What are you working on?</h2><div className="time-controls"><label>Project<select className="input" value={timerProject} onChange={e=>{setTimerProject(e.target.value);setTimerTask('');}}><option value="">Choose project</option>{data.projects?.filter(p=>!data.clients.find(c=>c.id===p.clientId)?.archivedAt).map(p=><option key={p.id} value={p.id}>{data.clients.find(c=>c.id===p.clientId)?.name} · {p.name}</option>)}</select></label><label>Task (optional)<select className="input" value={timerTask} onChange={e=>setTimerTask(e.target.value)}><option value="">Project time</option>{data.workItems.filter(w=>w.projectId===timerProject&&!w.archivedAt&&!data.workItems.some(c=>c.parentId===w.id)).map(w=><option key={w.id} value={w.id}>{w.title}</option>)}</select></label></div><div className="row"><button className="btn btn-primary" disabled={busy||!timerProject||!!activeTimer} onClick={()=>void run(async()=>{if(timerTask)await startTimer(timerTask);else{const r=await getSupabase().rpc('start_project_timer',{selected_project:timerProject});if(r.error)throw r.error;}})}>Start timer</button>{activeTimer&&<button className="btn" disabled={busy} onClick={()=>void run(stopTimer)}>Stop and save current timer</button>}<button className="btn" disabled={busy} onClick={()=>setEditing(null)}>Log time manually</button></div></section>}
 {error&&<p role="alert">{error}</p>}
 <section className="card time-controls" aria-label="Time report filters"><label>Period<select className="input" value={period} onChange={e=>{const p=e.target.value as Period;setPeriod(p);if(p!=='custom')setThrough(periodEnd(from,p));}}><option value="weekly">Weekly</option><option value="biweekly">Every two weeks</option><option value="semimonthly">Twice monthly</option><option value="monthly">Monthly</option><option value="custom">Custom</option></select></label><label>From<input type="date" className="input" value={from} onChange={e=>{setFrom(e.target.value);if(period!=='custom'&&e.target.value)setThrough(periodEnd(e.target.value,period));}}/></label><label>Through<input type="date" className="input" value={through} min={from} onChange={e=>{setThrough(e.target.value);setPeriod('custom');}}/></label><label>Client<select className="input" value={client} onChange={e=>{setClient(e.target.value);setProject('');}}><option value="">All clients</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Project<select className="input" value={project} onChange={e=>setProject(e.target.value)}><option value="">All projects</option>{data.projects?.filter(p=>!client||p.clientId===client).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{tab==='team'&&<label>Team member<select className="input" value={person} onChange={e=>setPerson(e.target.value)}><option value="">Everyone</option>{data.users.filter(u=>u.role!=='client').map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label>}<label>Billing<select className="input" value={billable} onChange={e=>setBillable(e.target.value)}><option value="">All time</option><option value="yes">Billable</option><option value="no">Nonbillable</option></select></label></section>
 <p className="muted">Dates use {Intl.DateTimeFormat().resolvedOptions().timeZone}. Entries crossing the range boundary contribute only their overlapping time. These are recorded hours, not processed payroll.</p>
 <div className="row"><strong>{(total/60).toFixed(2)} hours total</strong><span>{(billed/60).toFixed(2)} billable</span><span>{((total-billed)/60).toFixed(2)} nonbillable</span><button className="btn" onClick={exportRows}>Export CSV</button></div>
 {tab!=='tracker'&&<section className="card"><h2>{tab==='team'?'Hours by person':'Hours by project'}</h2>{Array.from(new Set(rows.map(r=>tab==='team'?r.e.userId:r.p?.id||''))).map(id=><p key={id}>{tab==='team'?data.users.find(u=>u.id===id)?.name:data.projects?.find(p=>p.id===id)?.name}: <strong>{(rows.filter(r=>(tab==='team'?r.e.userId:r.p?.id)===id).reduce((sum,r)=>sum+r.minutes,0)/60).toFixed(2)} hours</strong></p>)}</section>}
 <section className="stack" aria-label="Time entries">{!rows.length&&<p>No time entries in this range.</p>}{rows.map(({e,p,minutes})=><article className="card" key={e.id}><div className="row"><strong>{new Date(e.startedAt).toLocaleDateString()} · {(minutes/60).toFixed(2)} h</strong><span>{new Date(e.startedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}–{new Date(e.endedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span><span>{e.billable?'Billable':'Nonbillable'}</span></div><p>{data.clients.find(c=>c.id===p?.clientId)?.name} → {p?.name} → {data.workItems.find(w=>w.id===e.workItemId)?.title||'Project time'}</p><p>{data.users.find(u=>u.id===e.userId)?.name} · {e.note||'No note'}</p>{!supportSnapshot&&(team||e.userId===currentUser?.id)&&<div className="row"><button className="btn" disabled={busy} onClick={()=>setEditing(e)}>Edit entry</button><button className="btn btn-danger" disabled={busy} onClick={()=>void run(async()=>{await deleteTimeEntry(e.id);})}>Remove entry</button></div>}</article>)}</section>
 {editing!==undefined&&<TimeLogEditor entry={editing} onClose={()=>setEditing(undefined)} onSaved={async()=>{await refresh?.();setEditing(undefined);}}/>}
 </div>;
}
function TimeLogEditor({entry,onClose,onSaved}:{entry:TimeEntry|null;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [requestId]=useState(()=>crypto.randomUUID());
 const {data}=useAppState();const [project,setProject]=useState(entry?.projectId||''),[task,setTask]=useState(entry?.workItemId||'');
 const [start,setStart]=useState(localDateTime(entry?.startedAt||new Date(Date.now()-3600000).toISOString())),[end,setEnd]=useState(localDateTime(entry?.endedAt||new Date().toISOString()));
 const [note,setNote]=useState(entry?.note||''),[billable,setBillable]=useState(entry?.billable??true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <div className="modal-backdrop"><form className="modal" role="dialog" aria-modal="true" aria-label="Time entry" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await getSupabase().rpc('save_time_log',{request_id:requestId,entry_id:entry?.id||null,expected_updated_at:entry?.updatedAt||null,selected_project:project,selected_task:task||null,entry_start:new Date(start).toISOString(),entry_end:new Date(end).toISOString(),entry_note:note,entry_billable:billable});if(r.error)throw r.error;await onSaved();}catch(e){setError(typeof e==='object'&&e&&'message' in e?String(e.message):'Could not save entry.');}finally{setBusy(false);}}}><h2>{entry?'Edit time entry':'Log time'}</h2><p>Times use your device’s timezone. Corrections keep an audit history.</p><fieldset disabled={busy} className="project-fields"><label>Project<select className="input" required value={project} onChange={e=>{setProject(e.target.value);setTask('');}}><option value="">Choose project</option>{data.projects?.filter(p=>!data.clients.find(c=>c.id===p.clientId)?.archivedAt).map(p=><option key={p.id} value={p.id}>{data.clients.find(c=>c.id===p.clientId)?.name} · {p.name}</option>)}</select></label><label>Task (optional)<select className="input" value={task} onChange={e=>setTask(e.target.value)}><option value="">Project time</option>{data.workItems.filter(w=>w.projectId===project&&!w.archivedAt&&!data.workItems.some(c=>c.parentId===w.id)).map(w=><option key={w.id} value={w.id}>{w.title}</option>)}</select></label><label>Start<input className="input" required type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End<input className="input" required type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>Note<input className="input" maxLength={4000} value={note} onChange={e=>setNote(e.target.value)}/></label><label>Billable<input type="checkbox" checked={billable} onChange={e=>setBillable(e.target.checked)}/></label></fieldset>{error&&<p role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="btn" disabled={busy} onClick={onClose}>Cancel</button><button className="btn btn-primary" disabled={busy}>{busy?'Saving…':'Save entry'}</button></div></form></div>;
}
