import {useEffect,useState,useRef} from 'react';
import {useAppState} from '../context/AppStateContext';
import {isOwnerOrAdmin} from '../lib/permissions';
import {getSupabase} from '../lib/supabaseClient';
import {localDay,periodEnd,timeCsv,type Period} from '../lib/timeReporting';
import type {PayPeriod,PayrollData} from '../lib/payroll';
export function PayrollPanel(){
 const {currentUser,data,supportSnapshot}=useAppState();
 const account=useRef(currentUser?.id);account.current=currentUser?.id;
 const owner=isOwnerOrAdmin(currentUser),manager=owner||currentUser?.role==='supervisor';
 const [pay,setPay]=useState<PayrollData>({rates:[],periods:[]}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 const [member,setMember]=useState(currentUser?.id||''),[frequency,setFrequency]=useState<Period>('biweekly');
 const [first,setFirst]=useState(()=>localDay().slice(0,8)+'01'),[last,setLast]=useState(()=>periodEnd(localDay().slice(0,8)+'01','biweekly'));
 const [zone,setZone]=useState('America/Los_Angeles'),[rate,setRate]=useState(''),[currency,setCurrency]=useState('USD');
 const [returning,setReturning]=useState<PayPeriod|null>(null),[reason,setReason]=useState('');
 async function load(){const uid=account.current;const r=await getSupabase().rpc('payroll_data',{});if(r.error)throw r.error;if(uid!==account.current)return;setPay(r.data);setLoaded(true);}
 useEffect(()=>{setPay({rates:[],periods:[]});setLoaded(false);if(!supportSnapshot)void load().catch(e=>setError(e.message));},[currentUser?.id,supportSnapshot]);
 async function run(fn:()=>Promise<unknown>){if(busy)return;setBusy(true);setError('');try{await fn();await load();}catch(e){setError(typeof e==='object'&&e&&'message' in e?String(e.message):'Could not save payroll changes.');}finally{setBusy(false);}}
 async function transition(p:PayPeriod,action:string,why=''){const r=await getSupabase().rpc('change_pay_period',{period_id:p.id,expected_updated_at:p.updated_at,action,reason:why});if(r.error)throw r.error;}
 function exportLocked(){const text=timeCsv([['Person','From','Through','Timezone','Status','Recorded hours','Hourly rate','Currency','Base pay estimate'],...pay.periods.filter(p=>p.status==='locked').map(p=>[data.users.find(u=>u.id===p.user_id)?.name||p.user_id,p.starts_on,p.ends_on,p.timezone,p.status,(Number(p.minutes)/60).toFixed(4),p.hourly_rate??'',p.currency||'',p.hourly_rate===null?'':(Number(p.minutes)/60*Number(p.hourly_rate)).toFixed(2)])]);const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='sunrose-locked-periods.csv';a.click();URL.revokeObjectURL(url);}
 if(supportSnapshot)return <p>Payroll records are unavailable in support view. Review them from your own authorized account.</p>;
 return <section className="stack"><h2>Pay periods</h2><button className="btn" disabled={busy} onClick={()=>void run(async()=>{})}>Refresh periods</button><p>Review recorded hours, approve them, then lock the period. Pay estimates use all recorded hours, including nonbillable work. They exclude overtime premiums, taxes, deductions, and benefits.</p>
 {error&&<p role="alert">{error}</p>}
 {manager&&<form className="card stack" onSubmit={e=>{e.preventDefault();void run(async()=>{const r=await getSupabase().rpc('create_pay_period',{member,first_day:first,last_day:last,zone,frequency});if(r.error)throw r.error;});}}><h3>Create a pay period</h3><fieldset disabled={busy} className="time-controls"><label>Team member<select required className="input" value={member} onChange={e=>{setMember(e.target.value);setRate('');}}>{data.users.filter(u=>u.role!=='client'&&u.active!==false).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Schedule<select className="input" value={frequency} onChange={e=>{const f=e.target.value as Period;setFrequency(f);if(f!=='custom')setLast(periodEnd(first,f));}}><option value="weekly">Weekly</option><option value="biweekly">Every two weeks</option><option value="semimonthly">Twice monthly</option><option value="monthly">Monthly</option><option value="custom">Custom</option></select></label><label>First day<input className="input" required type="date" value={first} onChange={e=>{setFirst(e.target.value);if(e.target.value&&frequency!=='custom')setLast(periodEnd(e.target.value,frequency));}}/></label><label>Last day<input className="input" required type="date" min={first} value={last} onChange={e=>{setLast(e.target.value);setFrequency('custom');}}/></label><label>Timezone<select className="input" value={zone} onChange={e=>setZone(e.target.value)}>{Array.from(new Set(['America/Los_Angeles','America/Denver','America/Chicago','America/New_York','UTC',Intl.DateTimeFormat().resolvedOptions().timeZone])).map(z=><option key={z}>{z}</option>)}</select></label></fieldset><button className="btn btn-primary" disabled={busy}>Create draft period</button></form>}
 {owner&&<form className="card stack" onSubmit={e=>{e.preventDefault();void run(async()=>{const r=await getSupabase().rpc('set_staff_pay_rate',{member,rate:Number(rate),currency_code:currency});if(r.error)throw r.error;setRate('');});}}><h3>Pay rate · {data.users.find(u=>u.id===member)?.name}</h3><p>Current rate: {pay.rates.find(r=>r.user_id===member)?`${pay.rates.find(r=>r.user_id===member)?.hourly_rate} ${pay.rates.find(r=>r.user_id===member)?.currency}/hour`:'Not set'}. New rates apply to new periods. Existing draft periods have an explicit “Use current rate” action.</p><div className="time-controls"><label>Hourly pay rate<input className="input" required type="number" min="0" max="100000" step="0.01" value={rate} onChange={e=>setRate(e.target.value)}/></label><label>Currency<select className="input" value={currency} onChange={e=>setCurrency(e.target.value)}><option>USD</option><option>CAD</option><option>EUR</option><option>GBP</option></select></label></div><button className="btn" disabled={busy}>Save rate for future periods</button></form>}
 {owner&&<button className="btn" disabled={!pay.periods.some(p=>p.status==='locked')} onClick={exportLocked}>Export locked periods</button>}
 {!loaded&&!error&&<p>Loading pay periods…</p>}{loaded&&!pay.periods.length&&<p>No pay periods yet. A manager can create one for you.</p>}
 {pay.periods.map(p=><article className="card stack" key={p.id}><h3>{data.users.find(u=>u.id===p.user_id)?.name} · {p.starts_on}–{p.ends_on}</h3><p><span className="badge">{p.status}</span> · {p.timezone} · {p.cadence}</p><p>{p.status==='draft'?'Hours will be calculated when submitted.':`${(Number(p.minutes)/60).toFixed(2)} recorded hours`}</p>{owner&&<p>Period rate: {p.hourly_rate===null?'Not set':`${p.hourly_rate} ${p.currency}/hour`}{p.status!=='draft'&&p.hourly_rate!==null&&` · Base pay estimate: ${(Number(p.minutes)/60*Number(p.hourly_rate)).toFixed(2)} ${p.currency}`}</p>}{p.note&&<p>Correction note: {p.note}</p>}<div className="row">{p.status==='draft'&&<button className="btn btn-primary" disabled={busy} onClick={()=>void run(()=>transition(p,'submit'))}>Submit hours</button>}{p.status==='draft'&&manager&&<button className="btn" disabled={busy} onClick={()=>void run(()=>transition(p,'cancel'))}>Cancel draft period</button>}{p.status==='draft'&&owner&&<button className="btn" disabled={busy} onClick={()=>void run(()=>transition(p,'refresh_rate'))}>Use current rate</button>}{p.status==='submitted'&&manager&&(p.user_id!==currentUser?.id||owner)&&<button className="btn btn-primary" disabled={busy} onClick={()=>void run(()=>transition(p,'approve'))}>Approve hours</button>}{p.status==='approved'&&owner&&<button className="btn btn-primary" disabled={busy} onClick={()=>void run(()=>transition(p,'lock'))}>Lock period</button>}{!['draft','cancelled'].includes(p.status)&&manager&&(p.status!=='locked'||owner)&&<button className="btn" disabled={busy} onClick={()=>{setReturning(p);setReason('');}}>Return for correction</button>}</div></article>)}
 {returning&&<div className="modal-backdrop"><form className="modal" role="dialog" aria-modal="true" aria-label="Return period for correction" onSubmit={e=>{e.preventDefault();void run(async()=>{await transition(returning,'return',reason);setReturning(null);});}}><h3>Return for correction</h3><p>This reopens time editing and clears approval. The period must be submitted and approved again.</p><label>Reason<input className="input" required minLength={3} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="modal-actions"><button type="button" className="btn" disabled={busy} onClick={()=>setReturning(null)}>Cancel</button><button className="btn btn-primary" disabled={busy}>Return period</button></div></form></div>}
 </section>;
}
